// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

function getMigrationDatabaseUrl() {
  const directUrl = process.env["DIRECT_URL"]?.trim();
  if (directUrl) {
    return withConnectTimeout(directUrl);
  }

  const databaseUrl = process.env["DATABASE_URL"]?.trim();
  if (!databaseUrl) {
    return undefined;
  }

  const migrationUrl = databaseUrl.includes("-pooler.")
    ? databaseUrl.replace("-pooler.", ".")
    : databaseUrl;

  return withConnectTimeout(migrationUrl);
}

function withConnectTimeout(connectionString: string) {
  const url = new URL(connectionString);
  if (!url.searchParams.has("connect_timeout")) {
    url.searchParams.set("connect_timeout", "30");
  }
  return url.toString();
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: getMigrationDatabaseUrl(),
  },
});
