-- AlterTable
ALTER TABLE "Match" ADD COLUMN "player1Games" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Match" ADD COLUMN "player2Games" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Match" ADD COLUMN "scoreDetail" TEXT;
